#! /bin/sh


case "$1" in
start)
echo "Starting init script for Module Loading"
sh /usr/bin/scull_load
sh /usr/bin/module_load faulty
modprobe hello.ko

;;
stop)
echo "Removing user modules"
sh /usr/bin/scull_unload
sh /usr/bin/module_unload faulty
rmmod hello.ko

;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
